//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cLogin()
        {
            this.cLoginPhReportSalesInv = new HashSet<cLoginPhReportSalesInv>();
        }
    
        public int cLogId { get; set; }
        public string cLogPortal { get; set; }
        public string cLogEmpresa { get; set; }
        public string cLogUsuario { get; set; }
        public string cLogContrasenia { get; set; }
        public string cLogUrl { get; set; }
        public string cLogRutaDescarga { get; set; }
        public string cLogOutUrl { get; set; }
        public string RutaOTB { get; set; }
        public string RutaOBT_SellIn { get; set; }
        public string RutaOTB_SellIn_Plan { get; set; }
        public string vkorg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cLoginPhReportSalesInv> cLoginPhReportSalesInv { get; set; }
    }
}
