//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cProcesos
    {
        public string cProEmpresa { get; set; }
        public string cProSociedad { get; set; }
        public string cProProceso { get; set; }
        public int cProSecuencia { get; set; }
        public string cProTipo { get; set; }
        public string cProAtributo { get; set; }
        public string cProNombreAtributo { get; set; }
        public string cProValorAtributo { get; set; }
        public string cProAccion { get; set; }
        public Nullable<bool> cProHabilitar { get; set; }
    }
}
