//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstatusPH
    {
        public System.DateTime Fecha { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Intento { get; set; }
        public string TipoArchivo { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string Resultado { get; set; }
        public int idDescarga { get; set; }
    }
}
