//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalesPRODEntities : DbContext
    {
        public PortalesPRODEntities()
            : base("name=PortalesPRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARCHIVOS> ARCHIVOS { get; set; }
        public virtual DbSet<ARCHIVOS_log> ARCHIVOS_log { get; set; }
        public virtual DbSet<BuenFinMetas> BuenFinMetas { get; set; }
        public virtual DbSet<cLogin> cLogin { get; set; }
        public virtual DbSet<CONF_FTP> CONF_FTP { get; set; }
        public virtual DbSet<CONF_SECCION_LIVERPOOL> CONF_SECCION_LIVERPOOL { get; set; }
        public virtual DbSet<cProcesos> cProcesos { get; set; }
        public virtual DbSet<DESCARGAS> DESCARGAS { get; set; }
        public virtual DbSet<DETDESCARGAS_20012016> DETDESCARGAS_20012016 { get; set; }
        public virtual DbSet<DETDESCARGAS_26012017> DETDESCARGAS_26012017 { get; set; }
        public virtual DbSet<EstatusPH> EstatusPH { get; set; }
        public virtual DbSet<ARCHIVOS_SELLIN> ARCHIVOS_SELLIN { get; set; }
        public virtual DbSet<cLogin_Respaldo> cLogin_Respaldo { get; set; }
        public virtual DbSet<DETDESCARGAS> DETDESCARGAS { get; set; }
        public virtual DbSet<RECARGAS_CONF> RECARGAS_CONF { get; set; }
        public virtual DbSet<cLoginPhReportTypes> cLoginPhReportTypes { get; set; }
        public virtual DbSet<cLoginPhReportSalesInv> cLoginPhReportSalesInv { get; set; }
        public virtual DbSet<cLoginPhReportVariables> cLoginPhReportVariables { get; set; }
    }
}
