//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECARGAS_CONF
    {
        public System.DateTime Fecha { get; set; }
        public string USUARIO { get; set; }
        public string CADENA { get; set; }
        public bool STATUS { get; set; }
        public string TIPOARCHIVO { get; set; }
        public string RESULTADO { get; set; }
    }
}
